Reorganize how data is added to a plot.
With the addition of a Z coordinate matrix for 3-D plotting, things were getting a bit out of hand. Now we have:
	addcoords: adds x, y, Z, and configuration
	adderror: adds errorbar information
	addconf: adds axis configuration
This is a bit more verbose but much cleaner.